version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: flask
      POSTGRES_USER:  
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
